"use client"

/**
 * @fileoverview Global toast notification system.
 *
 * Implements a lightweight, framework-agnostic toast notification system
 * inspired by the react-hot-toast API.  The system is built around a
 * module-level state store and a publish-subscribe listener pattern, which
 * allows toast notifications to be triggered imperatively (outside of React
 * components) while still updating React state synchronously.
 *
 * Architecture overview:
 *  - `memoryState`  – The single source of truth for all active toasts, stored
 *                     outside of React so it survives component re-mounts.
 *  - `listeners`    – Array of `setState` callbacks registered by every
 *                     mounted `useToast` consumer.  `dispatch` calls each one.
 *  - `dispatch`     – Applies an action to `memoryState` via `reducer` and
 *                     notifies all registered listeners.
 *  - `toast()`      – Imperative helper to enqueue a new toast from anywhere.
 *  - `useToast()`   – React hook that subscribes a component to toast state.
 *
 * Usage:
 * ```ts
 * // Inside a React component:
 * const { toast } = useToast();
 * toast({ title: 'Saved!', description: 'Your changes were saved.' });
 *
 * // Imperatively from outside React (e.g. a service layer):
 * import { toast } from '@/hooks/use-toast';
 * toast({ variant: 'destructive', title: 'Error', description: 'Something went wrong.' });
 * ```
 *
 * @module hooks/use-toast
 */

import * as React from "react"

import type {
  ToastActionElement,
  ToastProps,
} from "@/components/ui/toast"

/** Maximum number of toasts visible simultaneously.  Oldest are removed when the limit is exceeded. */
const TOAST_LIMIT = 1

/**
 * Delay (in ms) before a dismissed toast is fully removed from the DOM.
 * The large value (~16 minutes) is intentional – dismissed toasts are hidden
 * via the `open: false` flag and will eventually be garbage-collected by this
 * timeout, preventing memory accumulation in very long-running sessions.
 */
const TOAST_REMOVE_DELAY = 1000000

/**
 * Extended toast type that merges the base Radix UI `ToastProps` with
 * application-level fields.  Every toast in the queue is represented by
 * an instance of this type.
 */
type ToasterToast = ToastProps & {
  /** Unique identifier generated by {@link genId} at creation time. */
  id: string
  title?: React.ReactNode
  description?: React.ReactNode
  action?: ToastActionElement
}

/** String literal constants for all dispatched action types, declared const for TypeScript narrowing. */
const actionTypes = {
  ADD_TOAST:     "ADD_TOAST",
  UPDATE_TOAST:  "UPDATE_TOAST",
  DISMISS_TOAST: "DISMISS_TOAST",
  REMOVE_TOAST:  "REMOVE_TOAST",
} as const

/** Module-level counter used to generate monotonically increasing toast IDs. */
let count = 0

/**
 * Generates a unique toast identifier by incrementing a module-level counter.
 * Wraps at `Number.MAX_SAFE_INTEGER` to prevent integer overflow in
 * extremely long-running browser sessions.
 *
 * @returns A string representation of the next unique toast ID.
 */
function genId() {
  count = (count + 1) % Number.MAX_SAFE_INTEGER
  return count.toString()
}

type ActionType = typeof actionTypes

type Action =
  | {
      type: ActionType["ADD_TOAST"]
      toast: ToasterToast
    }
  | {
      type: ActionType["UPDATE_TOAST"]
      toast: Partial<ToasterToast>
    }
  | {
      type: ActionType["DISMISS_TOAST"]
      toastId?: ToasterToast["id"]
    }
  | {
      type: ActionType["REMOVE_TOAST"]
      toastId?: ToasterToast["id"]
    }

interface State {
  /** The current queue of toasts rendered by the Toaster component. */
  toasts: ToasterToast[]
}

/**
 * Map of pending removal timeouts keyed by toast ID.
 * Used by {@link addToRemoveQueue} to ensure only one timeout is scheduled
 * per toast, preventing double-removal race conditions.
 */
const toastTimeouts = new Map<string, ReturnType<typeof setTimeout>>()

/**
 * Schedules a toast for removal from state after {@link TOAST_REMOVE_DELAY} ms.
 * Idempotent: if a timeout is already queued for the given ID, this is a no-op.
 *
 * @param toastId - The unique ID of the toast to schedule for removal.
 */
const addToRemoveQueue = (toastId: string) => {
  if (toastTimeouts.has(toastId)) {
    return
  }

  const timeout = setTimeout(() => {
    toastTimeouts.delete(toastId)
    dispatch({
      type: "REMOVE_TOAST",
      toastId: toastId,
    })
  }, TOAST_REMOVE_DELAY)

  toastTimeouts.set(toastId, timeout)
}

/**
 * Pure reducer function that computes the next toast state given the current
 * state and a dispatched action.  Follows the same Redux-style reducer pattern
 * used by React's `useReducer` hook.
 *
 * Cases:
 *  - `ADD_TOAST`     – Prepends the new toast and trims the array to TOAST_LIMIT.
 *  - `UPDATE_TOAST`  – Merges partial updates into the toast matching by ID.
 *  - `DISMISS_TOAST` – Sets `open: false` on one or all toasts and enqueues
 *                      their delayed removal.
 *  - `REMOVE_TOAST`  – Removes a specific toast (or clears all) from the queue.
 *
 * @param state  - Current toast queue state.
 * @param action - The dispatched action describing the state transition.
 * @returns The updated toast state.
 */
export const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case "ADD_TOAST":
      return {
        ...state,
        toasts: [action.toast, ...state.toasts].slice(0, TOAST_LIMIT),
      }

    case "UPDATE_TOAST":
      return {
        ...state,
        toasts: state.toasts.map((t) =>
          t.id === action.toast.id ? { ...t, ...action.toast } : t
        ),
      }

    case "DISMISS_TOAST": {
      const { toastId } = action

      // ! Side effects ! - This could be extracted into a dismissToast() action,
      // but I'll keep it here for simplicity
      if (toastId) {
        addToRemoveQueue(toastId)
      } else {
        state.toasts.forEach((toast) => {
          addToRemoveQueue(toast.id)
        })
      }

      return {
        ...state,
        toasts: state.toasts.map((t) =>
          t.id === toastId || toastId === undefined
            ? {
                ...t,
                open: false,
              }
            : t
        ),
      }
    }
    case "REMOVE_TOAST":
      if (action.toastId === undefined) {
        return {
          ...state,
          toasts: [],
        }
      }
      return {
        ...state,
        toasts: state.toasts.filter((t) => t.id !== action.toastId),
      }
  }
}

/** Array of `setState` callbacks from all currently mounted `useToast` consumers. */
const listeners: Array<(state: State) => void> = []

/** Module-level toast state – survives component unmounts and re-mounts. */
let memoryState: State = { toasts: [] }

/**
 * Applies an action to the module-level `memoryState` and synchronously
 * notifies all registered `useToast` listeners so their component state
 * updates in the same React render cycle.
 *
 * @param action - The action to apply via {@link reducer}.
 */
function dispatch(action: Action) {
  memoryState = reducer(memoryState, action)
  listeners.forEach((listener) => {
    listener(memoryState)
  })
}

/** Omit the `id` field from the public `toast()` API; IDs are generated internally. */
type Toast = Omit<ToasterToast, "id">

/**
 * Imperatively enqueues a new toast notification.
 *
 * Can be called from anywhere – inside or outside of React components –
 * making it suitable for use in service layers, error handlers, and
 * event listeners as well as UI code.
 *
 * @param props - Toast configuration (title, description, variant, action, etc.).
 * @returns An object with:
 *  - `id`      – The generated ID of the new toast.
 *  - `dismiss` – A function to programmatically dismiss this specific toast.
 *  - `update`  – A function to patch the toast's properties after creation.
 *
 * @example
 * const { dismiss } = toast({ title: 'Uploading...', description: 'Please wait.' });
 * // Later:
 * dismiss();
 */
function toast({ ...props }: Toast) {
  const id = genId()

  const update = (props: ToasterToast) =>
    dispatch({
      type: "UPDATE_TOAST",
      toast: { ...props, id },
    })
  const dismiss = () => dispatch({ type: "DISMISS_TOAST", toastId: id })

  dispatch({
    type: "ADD_TOAST",
    toast: {
      ...props,
      id,
      open: true,
      onOpenChange: (open) => {
        if (!open) dismiss()
      },
    },
  })

  return {
    id: id,
    dismiss,
    update,
  }
}

/**
 * React hook that subscribes a component to the global toast state and
 * returns both the current toast queue and helpers for triggering new toasts.
 *
 * Registers the component's `setState` in the module-level `listeners` array
 * on mount and deregisters it on unmount, ensuring that unmounted components
 * do not receive stale state updates.
 *
 * @returns An object containing:
 *  - `toasts`  – The current array of active `ToasterToast` objects.
 *  - `toast`   – The {@link toast} function for enqueuing new notifications.
 *  - `dismiss` – A function that dismisses a toast by ID (or all if omitted).
 *
 * @example
 * const { toast } = useToast();
 * toast({ title: 'Success', description: 'Settings saved.' });
 */
function useToast() {
  const [state, setState] = React.useState<State>(memoryState)

  React.useEffect(() => {
    listeners.push(setState)
    return () => {
      const index = listeners.indexOf(setState)
      if (index > -1) {
        listeners.splice(index, 1)
      }
    }
  }, [state])

  return {
    ...state,
    toast,
    dismiss: (toastId?: string) => dispatch({ type: "DISMISS_TOAST", toastId }),
  }
}

export { useToast, toast }
